default_language_version:
  python: python3.9

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: detect-private-key
